### PR TITLE
Fix cargo clippy warnings

### LINKED ISSUE #247: Update empty log macro implementations so they don't result in empty branch clippy warnings
The log macro wrappers provide an empty implementation when neither `log` or `defmt` is enabled. Several checks end up running with no features enabled so these empty implementations can get used. This can result in false clippy warnings with code like
```
if a {
    info!("Message A");
} else {
    info!("Message B");
}
```

Clippy will warning that both blocks here are empty/the same. See if we can change the empty macro implementation to either naturally suppress this warning or explicitly suppress it with a linter hint.

### PR DESCRIPTION
**Pull request by kurtjd**
This PR addresses all `cargo clippy` warnings.

Resolves #247

### CODE REVIEW

**Review by RobertZ2011 — APPROVED** [review]

**Comment by RobertZ2011** [comment]
> EXCEPT for await_holding_refcell_ref warnings as more clarification is needed if this is intentional and it is confirmed the risk of runtime panics is mitigated

These are intentional. At least in what I've written there shouldn't be any panics because the borrow happens at a single location and then the mutable reference is passed as an argument to other functions. But I'm open to switching over to synchronization types. I mostly avoided them because this code only runs in its own task and there may have been some situations where an async mutex lock wasn't compatible due to needing to be called in a non-async function.

**Comment by kurtjd** [comment]
> > EXCEPT for await_holding_refcell_ref warnings as more clarification is needed if this is intentional and it is confirmed the risk of runtime panics is mitigated
> 
> These are intentional. At least in what I've written there shouldn't be any panics because the borrow happens at a single location and then the mutable reference is passed as an argument to other functions. But I'm open to switching over to synchronization types. I mostly avoided them because this code only runs in its own task and there may have been some situations where an async mutex lock wasn't compatible due to needing to be called in a non-async function.

Sounds good, makes sense to me! I can just add an explicit clippy `allow` for this to suppress the warnings if everyone is okay with that.

File: type-c-service/src/task.rs [hunk 1]
```diff
@@ -83,6 +83,7 @@ impl Service {
                 connected: status.is_connected(),
             };
 
+            #[allow(clippy::if_same_then_else)]
```
[the remark this answers is not in the document]
Comment (RobertZ2011) [reply type-c-service/src/task.rs:86]: See this bug for some background: https://github.com/OpenDevicePartnership/embedded-services/issues/247. @kurtjd you might also see if moving this into the empty log macro definitions works to suppress the warning. Then we would be able to close out that bug as well.

[the remark this answers is not in the document]
Comment (madeleyneVaca) [reply type-c-service/src/task.rs:86]: gotcha. Thanks for the context!

[the remark this answers is not in the document]
Comment (kurtjd) [reply type-c-service/src/task.rs:86]: Thanks Robert, didn't see that issue. I will see if I can move the `allow` tag further into the macro itself.

[the remark this answers is not in the document]
Comment (kurtjd) [reply type-c-service/src/task.rs]: I was able to resolve this warning in the empty log functions by replacing:

```rust
let _ = ($( & $x ),*);
```

with:

```rust
let _ = ($s, $( &$x ),*);
```

However, when clippy is ran with the ```defmt``` feature, the warning is still generated, but strangely not the case when ran with the `log` feature. I couldn't really find a satisfying reason why, so I simply added the noop:

```rust
let _ = ($s, $( &$x ),*);
```

to the defmt log macros which worked.

**Comment by kurtjd** [comment]
> > EXCEPT for await_holding_refcell_ref warnings as more clarification is needed if this is intentional and it is confirmed the risk of runtime panics is mitigated
> 
> These are intentional. At least in what I've written there shouldn't be any panics because the borrow happens at a single location and then the mutable reference is passed as an argument to other functions. But I'm open to switching over to synchronization types. I mostly avoided them because this code only runs in its own task and there may have been some situations where an async mutex lock wasn't compatible due to needing to be called in a non-async function.

I decided to add the lint suppression to each offending method (as opposed to the crate as a whole) just to keep the scope narrow, but can do the opposite if it feels too cluttered.

**Comment by kurtjd** [comment]
The cargo vet error appears to be a problem on the server side? No dependencies were changed from main nor between force pushes.

**Review by jerrysxie — APPROVED** [review]

File: embedded-service/src/fmt.rs [hunk 2]
```diff
@@ -139,7 +144,7 @@ mod none {
     macro_rules! debug {
         ($s:literal $(, $x:expr)* $(,)?) => {
             {
-                let _ = ($( & $x ),*);
+                let _ = ($s, $( &$x ),*);
```
Comment (madeleyneVaca) [inline embedded-service/src/fmt.rs:147]: making sure I understand. This is so that in the "empty" cases, the parameters of the macros are technically "used" by this tuple that's created so they aren't flagged by clippy?

separately and maybe more of a @RobertZ2011 question. I understand the * usage in the macro definition so that we can have strings formatted with multiple args. but I'm not sure I understand it's usage in the tuple on this line

Comment (kurtjd) [reply embedded-service/src/fmt.rs:147]: That's my understanding, yeah. And I believe it shouldn't result in any actual generated code when compiled since it's effectively a noop (though if someone passes a function with side-effects as a parameter then hm, maybe code would be generated, so I'll double check).

For the * usage, my understanding is that this basically expands the parameters into comma-separated values within the tuple, thus making it seem like each parameter is being "used" as well, but Robert probably knows more.

Comment (madeleyneVaca) [reply embedded-service/src/fmt.rs:147]: I think what's throwing me off is that this is written as `( &$x ),*` where the comma is outside the parentheses for the `$x` reference instead of inside the parentheses like first usage of `*`

Comment (madeleyneVaca) [reply embedded-service/src/fmt.rs:147]: [macro_rules! - The Little Book of Rust Macros](https://fprijate.github.io/tlborm/mbe-macro-rules.html#repetitions)
the * repeats both the `(blah)` and the `,` wherein it's treating `,` as the separator. I was thinking in regex

Comment (RobertZ2011) [reply embedded-service/src/fmt.rs:147]: I mostly based that on how Embassy handles a similar situation, but my understand is the same as what Kurtis commented: it expands to a comma separated list. Macro syntax is weird in general unfortunately.

Comment (kurtjd) [reply embedded-service/src/fmt.rs:147]: To give an example from the output of `cargo expand`:

```rust
debug!("hello world: {}, {}, {}", 1, 2, 3);
```

expands to:

```rust
let _ = ("hello world: {}, {}, {}", &1, &2, &3);
```

when the macro is as follows:

```rust
    /// Logs a debug message using the underlying logger
    #[macro_export]
    #[collapse_debuginfo(yes)]
    macro_rules! debug {
        ($s:literal $(, $x:expr)* $(,)?) => {
            {
                let _ = ($s, $( &$x ),*);
            }
        };
    }
```
