### PR TITLE
Add SyncCell type to support Sync fix in embassy upstream

### LINKED ISSUE #361: Failure to compile with latest `embassy-sync`
After https://github.com/embassy-rs/embassy/pull/4320 merged, several bugs in ODP were exposed around improper `Sync` bounds. One of the major errors is `IntrusiveList` being used everywhere in `OnceLock`'s when `IntrusiveList` is `!Sync`

```Rust
error[E0277]: `core::cell::Cell<core::option::Option<&'static intrusive_list::IntrusiveNode>>` cannot be shared between threads safely         
   --> D:\.tools\.cargo\git\checkouts\embedded-services-78faf442f1f643c2\a938ac1\embedded-service\src\activity.rs:135:21
    |
135 | static SUBSCRIBERS: OnceLock<IntrusiveList> = OnceLock::new();
    |                     ^^^^^^^^^^^^^^^^^^^^^^^ `core::cell::Cell<core::option::Option<&'static intrusive_list::IntrusiveNode>>` cannot be shared between threads safely
    |
    = help: within `intrusive_list::IntrusiveList`, the trait `Sync` is not implemented for `core::cell::Cell<core::option::Option<&'static intrusive_list::IntrusiveNode>>`
    = note: if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock`
note: required because it appears within the type `intrusive_list::IntrusiveList`
   --> D:\.tools\.cargo\git\checkouts\embedded-services-78faf442f1f643c2\a938ac1\embedded-service\src\intrusive_list.rs:62:12
    |
62  | pub struct IntrusiveList {
    |            ^^^^^^^^^^^^^
    = note: required for `OnceLock<intrusive_list::IntrusiveList>` to implement `Sync`
    = note: shared static variables must have a type that implements `Sync`
```

### PR DESCRIPTION
**Pull request by JamesHuard**
Embassy upstream recently fixed accidentally adding Sync to non-Sync types: https://github.com/embassy-rs/embassy/pull/4320

In preparation to fix #361, added a drop-in replacement for Cell where moving to a proper primitive usage such as embassy_sync::mutex::Mutex is untenable. This also refactors the intrusive_list to utilize this new SyncCell type, allowing it to be used directly without any containers.

Note that in most cases SyncCell is not the best solution. If it is possible, proper synchronization primitives should be leveraged.

A critical section was used as opposed to a blocking_mutex type, as blocking_mutex is non-re-entrant. This allows the most flexibility in supporting scenarios with SyncCell, and does not require permutated get and set implementations based on mutex backing type.

In short:
- New SyncCell type introduced to unblock ingesting embassy upstream Sync fix
- We should use it sparingly
- IntrusiveList was updated to use this new type, allowing it to be allocated statically without any errors

### CODE REVIEW

File: embedded-service/src/sync_cell.rs [hunk 1]
```diff
@@ -0,0 +1,114 @@
+//! # SyncCell: a cell-like API for static interior mutability scenarios
+use core::cell::UnsafeCell;
+
+/// A critical section backed Cell for sync scenarios where you want Cell behaviors, but need it to be thread safe (such as used in statics)
+pub struct SyncCell<T: Copy> {
+    inner: UnsafeCell<T>,
```
Comment (asasine) [inline embedded-service/src/sync_cell.rs:6]: I think wrapping `Cell<T>` would be fine, and would eliminate all `unsafe` in the `SyncCell` implementation.

File: embedded-service/src/sync_cell.rs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+}
+
+impl<T: Copy> SyncCell<T> {
```
Comment (asasine) [inline embedded-service/src/sync_cell.rs:9]: I recommend implementing as much of the `Cell<T>` API as possible, including traits conditionally like `Clone`, `Default`, `Ord`, `PartialEq`, `Display`, etc.

**Review by gjpmsft — APPROVED** [review]

File: embedded-service/src/sync_cell.rs (hunk 1 above)
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs:6]: I wasn't sure if using Cell or UnsafeCell would be more "taboo" -- given I've seen SyncUnsafeCell in the unstable libs. I can definitely move to Cell if impl Sync over it is "as acceptable"

File: embedded-service/src/sync_cell.rs [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+    /// # Safety
+    /// This may be used safely if and only if the pointer is held during a critical section, or
+    /// all accessors to this Cell are blocked until the pointer is released.
+    pub unsafe fn as_ptr(&self) -> *mut T {
+        self.inner.get()
+    }
+}
+
+// SAFETY: Sync is implemented here for SyncCell as T is only accessed via nestable critical sections
+unsafe impl<T: Copy> Sync for SyncCell<T> {}
```
Comment (wmmc88) [inline embedded-service/src/sync_cell.rs:49]: You should also be able to `impl  Send` safely here (given that `T:Send`). [Cell does this too](https://doc.rust-lang.org/src/core/cell.rs.html#316)

Comment (wmmc88) [inline embedded-service/src/sync_cell.rs:49]: This doesn't necessarily need a `Sized` bound

File: embedded-service/src/sync_cell.rs [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+            *self.inner.get()
+        })
+    }
+
+    /// Sets the cell's content in a critical section. Note that this accounts
+    /// for read/write conditions but does not automatically handle logical data
+    /// race conditions. It is still possible for a user to read a value but have
+    /// it change after they've performed the read. This just ensures data integrity:
+    /// SyncCell<T> will always contain a valid T, even if it's been read "late"
+    pub fn set(&self, value: T) {
```
Comment (wmmc88) [inline embedded-service/src/sync_cell.rs:31]: `set` along with a lot of the other `Cell` apis(ex. `update`, `swap`) don't required `T: Copy`. Some apis don't even require `T:Sized` (although im not sure how useful that would even be here).

File: embedded-service/src/sync_cell.rs (hunk 3 above)
Comment (wmmc88) [reply embedded-service/src/sync_cell.rs:49]: actually maybe its fine to not relax to `T: ?Sized` since I can't think of a reason you'd use that in the context of the apis here (being wrapped with a crit section)

File: embedded-service/src/sync_cell.rs (hunk 2 above)
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs]: implemented

File: embedded-service/src/sync_cell.rs (hunk 4 above)
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs:22]: Moved around

File: embedded-service/src/sync_cell.rs [hunk 5]
```diff
@@ -0,0 +1,199 @@
...
+
+impl<T: Copy> SyncCell<T> {
+    /// Reads the cell's content (in a critical section) and returns a copy
+    pub fn get(&self) -> T {
+        critical_section::with(|_cs| self.inner.get())
+    }
+}
+
+impl<T: ?Sized> SyncCell<T> {
+    /// Unsafe: allows reads and writes without critical section guard, violating Sync guarantees.
```
[the remark this answers is not in the document]
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs:47]: Need it in intrusive_list

File: embedded-service/src/sync_cell.rs [hunk 6]
```diff
@@ -0,0 +1,199 @@
...
+    pub fn set(&self, value: T) {
+        critical_section::with(|_cs| self.inner.set(value))
+    }
+
+    /// Swap contents between two SyncCell's
+    pub fn swap(&self, other: &Self) {
+        critical_section::with(|_cs| self.inner.swap(&other.inner));
+    }
+
+    // we do not implement replace() as we cannot guarantee that it will not be called outside of compile time
```
[the remark this answers is not in the document]
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs:31]: Another option might be to make it const but also unsafe?

[the remark this answers is not in the document]
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs:31]: image

Oh, I might just drop this note all together since this is an unstable feature.

File: embedded-service/src/sync_cell.rs [hunk 7]
```diff
@@ -0,0 +1,199 @@
...
+    /// Sets the cell's content in a critical section. Note that this accounts
+    /// for read/write conditions but does not automatically handle logical data
+    /// race conditions. It is still possible for a user to read a value but have
+    /// it change after they've performed the read. This just ensures data integrity:
+    /// SyncCell<T> will always contain a valid T, even if it's been read "late"
+    pub fn set(&self, value: T) {
+        critical_section::with(|_cs| self.inner.set(value))
+    }
+
+    /// Swap contents between two SyncCell's
```
[the remark this answers is not in the document]
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs]: called out in two places

File: embedded-service/src/sync_cell.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs]: removed note entirely

File: embedded-service/src/sync_cell.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs:50]: Changed my mind after thinking on it more. If someone just wants to print the backing address, that is safe. So I will mark this safe but keep the safety section in the doc

File: embedded-service/src/sync_cell.rs (hunk 3 above)
Comment (asasine) [reply embedded-service/src/sync_cell.rs]: Is `dyn Trait` sized? You could use this to swap between different trait impls.

Comment (JamesHuard) [reply embedded-service/src/sync_cell.rs]: `&dyn Trait` is sized as one of those wide/fat pointer types. I don't think `dyn Trait` is inherently Sized

**Review by gjpmsft — APPROVED** [review]
